/**
 * Saajnika Luxury Mock Data Fixtures
 * Used for isolated frontend development and fallback testing.
 * Separated cleanly from the production API client.
 */

export const MOCK_CATEGORIES = [
  {
    id: 1,
    name: 'Haute Couture',
    slug: 'haute-couture',
    description: 'Masterpiece bespoke ensembles hand-embroidered with zardozi and pearls.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    item_count: 14,
    is_featured: true,
  },
  {
    id: 2,
    name: 'Banarasi Heirlooms',
    slug: 'banarasi-heirlooms',
    description: 'Pure Katan silk woven on traditional pit looms in Varanasi.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    item_count: 19,
    is_featured: true,
  },
  {
    id: 3,
    name: 'Contemporary Lehengas',
    slug: 'contemporary-lehengas',
    description: 'Modern silhouettes designed for the discerning modern bride and celebrations.',
    image: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=800&q=80',
    item_count: 22,
    is_featured: true,
  },
  {
    id: 4,
    name: 'Handcrafted Saris',
    slug: 'handcrafted-saris',
    description: 'Chanderi, organza, and tussar silk draperies with delicate mukaish work.',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    item_count: 28,
    is_featured: true,
  },
  {
    id: 5,
    name: 'Royal Anarkalis',
    slug: 'royal-anarkalis',
    description: 'Kalidar flared silhouettes embellished with antique dabka and gota patti.',
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
    item_count: 16,
    is_featured: false,
  },
  {
    id: 6,
    name: 'Bespoke Jewelry & Accessories',
    slug: 'jewelry-accessories',
    description: 'Artisanal kundan belts, potli purses, and hand-woven shawls.',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    item_count: 12,
    is_featured: false,
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 101,
    title: 'The Noor-e-Jahan Crimson Velvet Bridal Lehenga',
    slug: 'noor-e-jahan-crimson-velvet-lehenga',
    category: { id: 1, name: 'Haute Couture', slug: 'haute-couture' },
    price: 185000,
    original_price: 215000,
    discount_percentage: 14,
    is_in_stock: true,
    is_featured: true,
    is_new: true,
    sku: 'SAAJ-HC-001',
    description: 'Handcrafted in deep crimson silk velvet, this bridal lehenga is embellished with intricate antique gold zardozi, hand-cut sequins, and pearl accents. The ensemble includes a structured blouse with sweetheart neckline and twin tissue dupattas.',
    artisan_notes: 'Crafted over 480 man-hours by master zardozi craftsmen in Old Delhi and Lucknow atelier.',
    fabric_care: 'Pure Silk Velvet & Tissue Organza. Dry Clean Only. Store wrapped in pure muslin cloth.',
    primary_image: {
      url: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=1200&q=85',
      alt_text: 'Noor-e-Jahan Crimson Velvet Bridal Lehenga front view',
    },
    images: [
      { id: 1, url: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?auto=format&fit=crop&w=1200&q=85', alt_text: 'Front view' },
      { id: 2, url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85', alt_text: 'Intricate embroidery close-up' },
      { id: 3, url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85', alt_text: 'Back drape and silhouette' },
    ],
    available_colors: [
      { name: 'Crimson Vermilion', hex: '#8b0000' },
      { name: 'Imperial Plum', hex: '#4a154b' },
    ],
    available_sizes: ['XS', 'S', 'M', 'L', 'Custom Measurement'],
    variants: [
      { id: 1001, size: 'XS', color: 'Crimson Vermilion', stock: 2, price: 185000, sku: 'SAAJ-HC-001-XS-CR' },
      { id: 1002, size: 'S', color: 'Crimson Vermilion', stock: 4, price: 185000, sku: 'SAAJ-HC-001-S-CR' },
      { id: 1003, size: 'M', color: 'Crimson Vermilion', stock: 3, price: 185000, sku: 'SAAJ-HC-001-M-CR' },
      { id: 1004, size: 'L', color: 'Crimson Vermilion', stock: 1, price: 185000, sku: 'SAAJ-HC-001-L-CR' },
      { id: 1005, size: 'Custom Measurement', color: 'Crimson Vermilion', stock: 99, price: 195000, sku: 'SAAJ-HC-001-CUST-CR' },
    ],
  },
  {
    id: 102,
    title: 'The Zarina Gold Zari Tissue Banarasi Sari',
    slug: 'zarina-gold-zari-banarasi-sari',
    category: { id: 2, name: 'Banarasi Heirlooms', slug: 'banarasi-heirlooms' },
    price: 68000,
    original_price: 75000,
    discount_percentage: 9,
    is_in_stock: true,
    is_featured: true,
    is_new: true,
    sku: 'SAAJ-BH-002',
    description: 'Woven with real silver and gold gilded zari on featherlight tissue katan silk, featuring an exquisite shikargah motif pallu and scalloped border.',
    artisan_notes: 'Woven by National Award-winning weavers on Varanasi heritage jacquard pit looms.',
    fabric_care: 'Pure Katan Tissue Silk with Gold Gilded Zari. Professional dry clean only.',
    primary_image: {
      url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=85',
      alt_text: 'Zarina Gold Zari Tissue Banarasi Sari',
    },
    images: [
      { id: 4, url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=85', alt_text: 'Front drape' },
      { id: 5, url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85', alt_text: 'Pallu detail' },
    ],
    available_colors: [
      { name: 'Liquid Champagne Gold', hex: '#d4af37' },
      { name: 'Rose Gold Shimmer', hex: '#e0a899' },
    ],
    available_sizes: ['One Size (Free Size)'],
    variants: [
      { id: 1006, size: 'One Size (Free Size)', color: 'Liquid Champagne Gold', stock: 5, price: 68000, sku: 'SAAJ-BH-002-GOLD' },
      { id: 1007, size: 'One Size (Free Size)', color: 'Rose Gold Shimmer', stock: 3, price: 68000, sku: 'SAAJ-BH-002-ROSE' },
    ],
  },
  {
    id: 103,
    title: 'The Mehr-un-Nisa Emerald Velvet Kalidar Anarkali',
    slug: 'mehr-un-nisa-emerald-velvet-anarkali',
    category: { id: 5, name: 'Royal Anarkalis', slug: 'royal-anarkalis' },
    price: 94000,
    original_price: 105000,
    discount_percentage: 10,
    is_in_stock: true,
    is_featured: false,
    is_new: false,
    sku: 'SAAJ-RA-003',
    description: '36-kali flared floor-length anarkali in rich emerald green micro-velvet, laden with marodi hand-embroidery and antique gota borders.',
    artisan_notes: 'Signature royal flare created with authentic Rajasthani gota work.',
    fabric_care: 'Micro Velvet & Chiffon Dupatta. Dry clean only.',
    primary_image: {
      url: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
      alt_text: 'Emerald Velvet Kalidar Anarkali',
    },
    images: [
      { id: 6, url: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85', alt_text: 'Full flare' },
      { id: 7, url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85', alt_text: 'Bodice embroidery' },
    ],
    available_colors: [
      { name: 'Imperial Emerald', hex: '#0f52ba' },
      { name: 'Midnight Obsidian', hex: '#111116' },
    ],
    available_sizes: ['S', 'M', 'L', 'XL'],
    variants: [
      { id: 1008, size: 'S', color: 'Imperial Emerald', stock: 2, price: 94000, sku: 'SAAJ-RA-003-S-EM' },
      { id: 1009, size: 'M', color: 'Imperial Emerald', stock: 4, price: 94000, sku: 'SAAJ-RA-003-M-EM' },
      { id: 1010, size: 'L', color: 'Imperial Emerald', stock: 2, price: 94000, sku: 'SAAJ-RA-003-L-EM' },
      { id: 1011, size: 'XL', color: 'Imperial Emerald', stock: 0, price: 94000, sku: 'SAAJ-RA-003-XL-EM' },
    ],
  },
  {
    id: 104,
    title: 'The Chandrakala Ivory Organza Chanderi Sari',
    slug: 'chandrakala-ivory-organza-sari',
    category: { id: 4, name: 'Handcrafted Saris', slug: 'handcrafted-saris' },
    price: 46000,
    original_price: 52000,
    discount_percentage: 11,
    is_in_stock: true,
    is_featured: true,
    is_new: true,
    sku: 'SAAJ-HS-004',
    description: 'Ethereal ivory silk organza hand-painted with botanical motifs and bordered with delicate silver mukaish needlework and pearl scallops.',
    artisan_notes: 'Hand-painted by botanical artists in Santiniketan.',
    fabric_care: 'Pure Silk Organza. Steam iron on reverse. Dry clean only.',
    primary_image: {
      url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85',
      alt_text: 'Chandrakala Ivory Organza Sari',
    },
    images: [
      { id: 8, url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=85', alt_text: 'Ivory organza drape' },
    ],
    available_colors: [
      { name: 'Pristine Ivory', hex: '#fdfbf7' },
      { name: 'Blush Pearl', hex: '#f7e7e6' },
    ],
    available_sizes: ['One Size (Free Size)'],
    variants: [
      { id: 1012, size: 'One Size (Free Size)', color: 'Pristine Ivory', stock: 6, price: 46000, sku: 'SAAJ-HS-004-IVORY' },
    ],
  },
  {
    id: 105,
    title: 'The Gulzar Blush Pink Georgette Lehenga',
    slug: 'gulzar-blush-pink-georgette-lehenga',
    category: { id: 3, name: 'Contemporary Lehengas', slug: 'contemporary-lehengas' },
    price: 135000,
    original_price: 150000,
    discount_percentage: 10,
    is_in_stock: true,
    is_featured: true,
    is_new: false,
    sku: 'SAAJ-CL-005',
    description: 'Pastel blush silk georgette adorned with resham threadwork, micro-cut crystals, and tonal glass beads. Accompanied by a corset blouse.',
    artisan_notes: 'Tone-on-tone French knot and resham embroidery.',
    fabric_care: 'Silk Georgette & Net. Dry clean only.',
    primary_image: {
      url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85',
      alt_text: 'Gulzar Blush Pink Georgette Lehenga',
    },
    images: [
      { id: 9, url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=85', alt_text: 'Blush pink lehenga' },
    ],
    available_colors: [
      { name: 'Blush Petal', hex: '#f4c2c2' },
      { name: 'Dusty Rose', hex: '#dcae96' },
    ],
    available_sizes: ['XS', 'S', 'M', 'L'],
    variants: [
      { id: 1013, size: 'XS', color: 'Blush Petal', stock: 1, price: 135000, sku: 'SAAJ-CL-005-XS' },
      { id: 1014, size: 'S', color: 'Blush Petal', stock: 3, price: 135000, sku: 'SAAJ-CL-005-S' },
      { id: 1015, size: 'M', color: 'Blush Petal', stock: 2, price: 135000, sku: 'SAAJ-CL-005-M' },
    ],
  },
  {
    id: 106,
    title: 'The Sheesh Mahal Kundan & Polki Bridal Choker Set',
    slug: 'sheesh-mahal-kundan-polki-choker',
    category: { id: 6, name: 'Bespoke Jewelry & Accessories', slug: 'jewelry-accessories' },
    price: 52000,
    original_price: 58000,
    discount_percentage: 10,
    is_in_stock: true,
    is_featured: false,
    is_new: true,
    sku: 'SAAJ-JA-006',
    description: 'Handcrafted 24k gold gilded silver choker with uncut polki, natural emerald beads, and Basra pearl drops.',
    artisan_notes: 'Jaipur jadau kundan craftsmanship with meenakari enameling on reverse.',
    fabric_care: '92.5 Silver with 24k Gold Dip. Keep in velvet box, avoid perfume and moisture.',
    primary_image: {
      url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85',
      alt_text: 'Sheesh Mahal Kundan Choker Set',
    },
    images: [
      { id: 10, url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85', alt_text: 'Choker set' },
    ],
    available_colors: [
      { name: 'Antique Jadau Gold', hex: '#d4af37' },
    ],
    available_sizes: ['One Size (Adjustable Dori)'],
    variants: [
      { id: 1016, size: 'One Size (Adjustable Dori)', color: 'Antique Jadau Gold', stock: 4, price: 52000, sku: 'SAAJ-JA-006-STD' },
    ],
  },
];

export const MOCK_COUPONS = [
  {
    code: 'SAAJNIKA10',
    discount_type: 'PERCENTAGE',
    discount_value: 10,
    max_discount: 15000,
    min_order_value: 30000,
    description: '10% privilege discount on bespoke couture orders above ₹30,000.',
  },
  {
    code: 'COUTURE15',
    discount_type: 'PERCENTAGE',
    discount_value: 15,
    max_discount: 25000,
    min_order_value: 75000,
    description: '15% bridal tier discount for curated orders above ₹75,000.',
  },
  {
    code: 'ROYAL5000',
    discount_type: 'FIXED',
    discount_value: 5000,
    min_order_value: 50000,
    description: 'Flat ₹5,000 savings on bridal and heirloom saris.',
  },
];

export const MOCK_USER = {
  id: 1,
  first_name: 'Kavya',
  last_name: 'Singhania',
  email: 'kavya.singhania@example.com',
  phone: '9876543210',
  is_staff: true,
  is_superuser: true,
  role: 'VIP Concierge Client',
  member_since: '2024-04-12',
  measurements: {
    bust: '34 in',
    waist: '28 in',
    hips: '38 in',
    shoulder: '14.5 in',
    blouse_length: '14 in',
    lehenga_length: '43 in',
  },
};

export const MOCK_ADDRESSES = [
  {
    id: 1,
    name: 'Kavya Singhania',
    phone: '9876543210',
    address_line_1: 'Villa 14, The Magnolias, Golf Course Road',
    address_line_2: 'DLF Phase 5',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    is_default: true,
    type: 'Residence',
  },
  {
    id: 2,
    name: 'Kavya Singhania (Atelier Office)',
    phone: '9876543210',
    address_line_1: 'Penthouse 4B, One Horizon Center',
    address_line_2: 'Golf Course Road',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    is_default: false,
    type: 'Office',
  },
];

export const MOCK_ORDERS = [
  {
    id: 'SAAJ-ORD-89421',
    created_at: '2026-10-02T14:30:00Z',
    status: 'SHIPPED',
    payment_status: 'PAID',
    payment_method: 'Razorpay (UPI / NetBanking)',
    transaction_id: 'pay_Nz82hK91mLPq11',
    tracking_number: 'SR-DEL-98412093',
    courier_partner: 'Shiprocket White Glove Luxury Logistics',
    estimated_delivery: '2026-10-10',
    shipping_address: MOCK_ADDRESSES[0],
    subtotal: 185000,
    discount_amount: 18500,
    applied_coupon: 'SAAJNIKA10',
    gst_amount: 19980,
    shipping_fee: 0,
    total_amount: 186480,
    timeline: [
      { status: 'CREATED', label: 'Bespoke Order Placed', timestamp: '2026-10-02 14:30', completed: true },
      { status: 'PAID', label: 'Payment Authenticated', timestamp: '2026-10-02 14:32', completed: true },
      { status: 'PROCESSING', label: 'Master Artisan Hand-Crafting', timestamp: '2026-10-04 10:15', completed: true },
      { status: 'PACKED', label: 'Atelier Velvet Packaging & Seal', timestamp: '2026-10-06 16:45', completed: true },
      { status: 'SHIPPED', label: 'Dispatched via White Glove Express', timestamp: '2026-10-07 09:30', completed: true },
      { status: 'OUT_FOR_DELIVERY', label: 'Out for Private Courier Handover', timestamp: null, completed: false },
      { status: 'DELIVERED', label: 'Delivered into Customer Hands', timestamp: null, completed: false },
    ],
    items: [
      {
        id: 1,
        product: MOCK_PRODUCTS[0],
        variant: MOCK_PRODUCTS[0].variants[1],
        quantity: 1,
        unit_price: 185000,
        subtotal: 185000,
      },
    ],
  },
  {
    id: 'SAAJ-ORD-88104',
    created_at: '2026-09-18T11:20:00Z',
    status: 'DELIVERED',
    payment_status: 'PAID',
    payment_method: 'Razorpay (HDFC Infina)',
    transaction_id: 'pay_Mx102nB8871KkL',
    tracking_number: 'SR-DEL-87102931',
    courier_partner: 'Shiprocket White Glove Logistics',
    estimated_delivery: '2026-09-23',
    shipping_address: MOCK_ADDRESSES[0],
    subtotal: 68000,
    discount_amount: 5000,
    applied_coupon: 'ROYAL5000',
    gst_amount: 7560,
    shipping_fee: 0,
    total_amount: 70560,
    timeline: [
      { status: 'CREATED', label: 'Order Placed', timestamp: '2026-09-18 11:20', completed: true },
      { status: 'PAID', label: 'Payment Confirmed', timestamp: '2026-09-18 11:22', completed: true },
      { status: 'PACKED', label: 'Packaged & Certified', timestamp: '2026-09-19 14:00', completed: true },
      { status: 'SHIPPED', label: 'Dispatched', timestamp: '2026-09-20 10:00', completed: true },
      { status: 'DELIVERED', label: 'Delivered', timestamp: '2026-09-22 17:30', completed: true },
    ],
    items: [
      {
        id: 2,
        product: MOCK_PRODUCTS[1],
        variant: MOCK_PRODUCTS[1].variants[0],
        quantity: 1,
        unit_price: 68000,
        subtotal: 68000,
      },
    ],
  },
];

export const MOCK_ADMIN_STATS = {
  total_revenue: 4892000,
  orders_count: 38,
  pending_orders: 5,
  total_customers: 214,
  low_stock_items: 3,
  conversion_rate: '4.8%',
  average_order_value: 128736,
  recent_activities: [
    { id: 1, action: 'Order #SAAJ-ORD-89421 marked as Shipped', user: 'Ops Admin', timestamp: '10 mins ago' },
    { id: 2, action: 'Stock replenished for Zarina Tissue Sari (+5 units)', user: 'Inventory Lead', timestamp: '1 hour ago' },
    { id: 3, action: 'Bespoke Concierge appointment booked by Shreya Mehta', user: 'Concierge Desk', timestamp: '3 hours ago' },
    { id: 4, action: 'New VIP Customer joined via OTP authentication', user: 'System', timestamp: '5 hours ago' },
  ],
};
